# Generated by Django 4.2.11 on 2024-03-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("jan", models.FloatField()),
                ("feb", models.FloatField()),
                ("mar", models.FloatField()),
                ("apr", models.FloatField()),
                ("may", models.FloatField()),
                ("jun", models.FloatField()),
                ("jul", models.FloatField()),
                ("aug", models.FloatField()),
                ("sep", models.FloatField()),
                ("oct", models.FloatField()),
                ("nov", models.FloatField()),
                ("dec", models.FloatField()),
                ("win", models.FloatField(blank=True, null=True)),
                ("spr", models.FloatField(blank=True, null=True)),
                ("sum", models.FloatField(blank=True, null=True)),
                ("aut", models.FloatField(blank=True, null=True)),
                ("ann", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
